module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  rootDir: '.',
  testMatch: ['<rootDir>/tests/unit/**/*.spec.ts'],
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['src/domain/use-cases/**/*.ts'],
  coverageDirectory: './coverage/unit',
  coverageReporters: ['text', 'lcov', 'html'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/'],
  moduleNameMapper: {
    '^~/(.*)$': '<rootDir>/src/$1',
    '^~config/(.*)$': '<rootDir>/src/config/$1',
    '^~domain/(.*)$': '<rootDir>/src/domain/$1',
    '^~nestjs/(.*)$': '<rootDir>/src/nestjs/$1',
  },
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  testTimeout: 10000,
  verbose: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
};
